Remove quiver dependency, instead use hash functions provided by Dart
google/tuple.dart pull request #33
Opened 2021-12-21 16:28 UTC by cenumi

2022-05-05 10:04 UTC, shilangyu commented
Bump, I think this is a beneficial change.

2022-10-04 17:14 UTC, devoncarew commented
@kevmoo for review as he has commit access here (this change looks good to me)

2022-10-04 17:15 UTC, kevmoo requested changes

2022-10-04 17:15 UTC, kevmoo commented on pubspec.yaml
>  repository: https://github.com/google/tuple.dart
☝️  change the version to 2.0.1 and add a changelog entry!

2022-10-04 18:12 UTC, devoncarew commented
> change the version to 2.0.1 and add a changelog entry

I'll land this and update the changelog +version in a follow-up.

2022-10-04 18:12 UTC, merged